'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace smsService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.laotel.com", ConfigurationName:="smsService.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckOnlineWifi_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckOnlineWifi_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/GetPasswordWifi_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetPasswordWifi_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/QueryPackageWifi_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function QueryPackageWifi_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CallWebService", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CallWebService(ByVal cmd As String, ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/SubmitSMS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SubmitSMS(ByVal NameAPP As String, ByVal Header As String, ByVal Msisdn As String, ByVal Msg As String, ByVal UserID As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/SelectLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SelectLog(ByVal params As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/RequestProductByID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RequestProductByID(ByVal product_type As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/HSPA", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HSPA() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/PreP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreP() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/PostP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PostP() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckNetwrokType_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckNetwrokType_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckBalancePostPaid_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckBalancePostPaid_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/RefillCard_PostPaid_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RefillCard_PostPaid_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/RefillCard_PSTN_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RefillCard_PSTN_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckPoint_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckPoint_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckBalancePrePaid_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckBalancePrePaid_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckDataServicePrePaid_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckDataServicePrePaid_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckPackageData_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckPackageData_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckPackageDataHSPA_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckPackageDataHSPA_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/RefillCard_PrePaid_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RefillCard_PrePaid_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/GetCustomerInfo_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCustomerInfo_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/SubmitSMS_cmd_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SubmitSMS_cmd_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/SetPackagePrePaid_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SetPackagePrePaid_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/Register_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Register_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckUserAndPassword_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckUserAndPassword_Json(ByVal Params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/ChangePasswordUserName_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ChangePasswordUserName_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/RequestProductByID_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RequestProductByID_Json(ByVal product_type As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/SelectLog_json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SelectLog_json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/TranferBalanceOCS_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TranferBalanceOCS_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/CheckBalancePSTN_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CheckBalancePSTN_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/AuthenMBill_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AuthenMBill_Json(ByVal param As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/RequestListNumber", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RequestListNumber(ByVal Email As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/RegisterMBill_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RegisterMBill_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/RegisterWifi_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RegisterWifi_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/BuyPackageWifi_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BuyPackageWifi_Json(ByVal params As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.laotel.com/ChangePasswordWifi_Json", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ChangePasswordWifi_Json(ByVal params As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits smsService.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of smsService.ServiceSoap)
        Implements smsService.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CheckOnlineWifi_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckOnlineWifi_Json
            Return MyBase.Channel.CheckOnlineWifi_Json(params)
        End Function
        
        Public Function GetPasswordWifi_Json(ByVal params As String) As String Implements smsService.ServiceSoap.GetPasswordWifi_Json
            Return MyBase.Channel.GetPasswordWifi_Json(params)
        End Function
        
        Public Function QueryPackageWifi_Json(ByVal params As String) As String Implements smsService.ServiceSoap.QueryPackageWifi_Json
            Return MyBase.Channel.QueryPackageWifi_Json(params)
        End Function
        
        Public Function CallWebService(ByVal cmd As String, ByVal params As String) As String Implements smsService.ServiceSoap.CallWebService
            Return MyBase.Channel.CallWebService(cmd, params)
        End Function
        
        Public Function SubmitSMS(ByVal NameAPP As String, ByVal Header As String, ByVal Msisdn As String, ByVal Msg As String, ByVal UserID As String) As String Implements smsService.ServiceSoap.SubmitSMS
            Return MyBase.Channel.SubmitSMS(NameAPP, Header, Msisdn, Msg, UserID)
        End Function
        
        Public Function SelectLog(ByVal params As String) As System.Data.DataTable Implements smsService.ServiceSoap.SelectLog
            Return MyBase.Channel.SelectLog(params)
        End Function
        
        Public Function RequestProductByID(ByVal product_type As String) As System.Data.DataTable Implements smsService.ServiceSoap.RequestProductByID
            Return MyBase.Channel.RequestProductByID(product_type)
        End Function
        
        Public Function HSPA() As System.Data.DataTable Implements smsService.ServiceSoap.HSPA
            Return MyBase.Channel.HSPA
        End Function
        
        Public Function PreP() As System.Data.DataTable Implements smsService.ServiceSoap.PreP
            Return MyBase.Channel.PreP
        End Function
        
        Public Function PostP() As System.Data.DataTable Implements smsService.ServiceSoap.PostP
            Return MyBase.Channel.PostP
        End Function
        
        Public Function CheckNetwrokType_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckNetwrokType_Json
            Return MyBase.Channel.CheckNetwrokType_Json(params)
        End Function
        
        Public Function CheckBalancePostPaid_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckBalancePostPaid_Json
            Return MyBase.Channel.CheckBalancePostPaid_Json(params)
        End Function
        
        Public Function RefillCard_PostPaid_Json(ByVal params As String) As String Implements smsService.ServiceSoap.RefillCard_PostPaid_Json
            Return MyBase.Channel.RefillCard_PostPaid_Json(params)
        End Function
        
        Public Function RefillCard_PSTN_Json(ByVal params As String) As String Implements smsService.ServiceSoap.RefillCard_PSTN_Json
            Return MyBase.Channel.RefillCard_PSTN_Json(params)
        End Function
        
        Public Function CheckPoint_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckPoint_Json
            Return MyBase.Channel.CheckPoint_Json(params)
        End Function
        
        Public Function CheckBalancePrePaid_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckBalancePrePaid_Json
            Return MyBase.Channel.CheckBalancePrePaid_Json(params)
        End Function
        
        Public Function CheckDataServicePrePaid_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckDataServicePrePaid_Json
            Return MyBase.Channel.CheckDataServicePrePaid_Json(params)
        End Function
        
        Public Function CheckPackageData_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckPackageData_Json
            Return MyBase.Channel.CheckPackageData_Json(params)
        End Function
        
        Public Function CheckPackageDataHSPA_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckPackageDataHSPA_Json
            Return MyBase.Channel.CheckPackageDataHSPA_Json(params)
        End Function
        
        Public Function RefillCard_PrePaid_Json(ByVal params As String) As String Implements smsService.ServiceSoap.RefillCard_PrePaid_Json
            Return MyBase.Channel.RefillCard_PrePaid_Json(params)
        End Function
        
        Public Function GetCustomerInfo_Json(ByVal params As String) As String Implements smsService.ServiceSoap.GetCustomerInfo_Json
            Return MyBase.Channel.GetCustomerInfo_Json(params)
        End Function
        
        Public Function SubmitSMS_cmd_Json(ByVal params As String) As String Implements smsService.ServiceSoap.SubmitSMS_cmd_Json
            Return MyBase.Channel.SubmitSMS_cmd_Json(params)
        End Function
        
        Public Function SetPackagePrePaid_Json(ByVal params As String) As String Implements smsService.ServiceSoap.SetPackagePrePaid_Json
            Return MyBase.Channel.SetPackagePrePaid_Json(params)
        End Function
        
        Public Function Register_Json(ByVal params As String) As String Implements smsService.ServiceSoap.Register_Json
            Return MyBase.Channel.Register_Json(params)
        End Function
        
        Public Function CheckUserAndPassword_Json(ByVal Params As String) As String Implements smsService.ServiceSoap.CheckUserAndPassword_Json
            Return MyBase.Channel.CheckUserAndPassword_Json(Params)
        End Function
        
        Public Function ChangePasswordUserName_Json(ByVal params As String) As String Implements smsService.ServiceSoap.ChangePasswordUserName_Json
            Return MyBase.Channel.ChangePasswordUserName_Json(params)
        End Function
        
        Public Function RequestProductByID_Json(ByVal product_type As String) As String Implements smsService.ServiceSoap.RequestProductByID_Json
            Return MyBase.Channel.RequestProductByID_Json(product_type)
        End Function
        
        Public Function SelectLog_json(ByVal params As String) As String Implements smsService.ServiceSoap.SelectLog_json
            Return MyBase.Channel.SelectLog_json(params)
        End Function
        
        Public Function TranferBalanceOCS_Json(ByVal params As String) As String Implements smsService.ServiceSoap.TranferBalanceOCS_Json
            Return MyBase.Channel.TranferBalanceOCS_Json(params)
        End Function
        
        Public Function CheckBalancePSTN_Json(ByVal params As String) As String Implements smsService.ServiceSoap.CheckBalancePSTN_Json
            Return MyBase.Channel.CheckBalancePSTN_Json(params)
        End Function
        
        Public Function AuthenMBill_Json(ByVal param As String) As String Implements smsService.ServiceSoap.AuthenMBill_Json
            Return MyBase.Channel.AuthenMBill_Json(param)
        End Function
        
        Public Function RequestListNumber(ByVal Email As String) As String Implements smsService.ServiceSoap.RequestListNumber
            Return MyBase.Channel.RequestListNumber(Email)
        End Function
        
        Public Function RegisterMBill_Json(ByVal params As String) As String Implements smsService.ServiceSoap.RegisterMBill_Json
            Return MyBase.Channel.RegisterMBill_Json(params)
        End Function
        
        Public Function RegisterWifi_Json(ByVal params As String) As String Implements smsService.ServiceSoap.RegisterWifi_Json
            Return MyBase.Channel.RegisterWifi_Json(params)
        End Function
        
        Public Function BuyPackageWifi_Json(ByVal params As String) As String Implements smsService.ServiceSoap.BuyPackageWifi_Json
            Return MyBase.Channel.BuyPackageWifi_Json(params)
        End Function
        
        Public Function ChangePasswordWifi_Json(ByVal params As String) As String Implements smsService.ServiceSoap.ChangePasswordWifi_Json
            Return MyBase.Channel.ChangePasswordWifi_Json(params)
        End Function
    End Class
End Namespace
