//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConfirmTopup.ltcsrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LTCServiceSoap", Namespace="http://services.laotel.com/")]
    public partial class LTCService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback changePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBalanceNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelReceiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuyTopupOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuyTopupFreeAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkBalanceCenterOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkBalanceCenterNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBalancePrepaidOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSHeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryDetailMobileOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryDetailMasterSimOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckTransactionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckProductTypeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LTCService() {
            this.Url = global::ConfirmTopup.Properties.Settings.Default.ConfirmTopup_ltcsrv_LTCService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event changePasswordCompletedEventHandler changePasswordCompleted;
        
        /// <remarks/>
        public event CheckInformationCompletedEventHandler CheckInformationCompleted;
        
        /// <remarks/>
        public event CheckBalanceCompletedEventHandler CheckBalanceCompleted;
        
        /// <remarks/>
        public event CheckBalanceNewCompletedEventHandler CheckBalanceNewCompleted;
        
        /// <remarks/>
        public event PaymentCompletedEventHandler PaymentCompleted;
        
        /// <remarks/>
        public event CancelReceiptCompletedEventHandler CancelReceiptCompleted;
        
        /// <remarks/>
        public event BuyTopupCompletedEventHandler BuyTopupCompleted;
        
        /// <remarks/>
        public event BuyTopupFreeAmountCompletedEventHandler BuyTopupFreeAmountCompleted;
        
        /// <remarks/>
        public event checkBalanceCenterCompletedEventHandler checkBalanceCenterCompleted;
        
        /// <remarks/>
        public event checkBalanceCenterNewCompletedEventHandler checkBalanceCenterNewCompleted;
        
        /// <remarks/>
        public event CheckBalancePrepaidCompletedEventHandler CheckBalancePrepaidCompleted;
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        public event SendSMSHeaderCompletedEventHandler SendSMSHeaderCompleted;
        
        /// <remarks/>
        public event QueryDetailCompletedEventHandler QueryDetailCompleted;
        
        /// <remarks/>
        public event QueryDetailMobileCompletedEventHandler QueryDetailMobileCompleted;
        
        /// <remarks/>
        public event QueryDetailMasterSimCompletedEventHandler QueryDetailMasterSimCompleted;
        
        /// <remarks/>
        public event CheckTransactionIDCompletedEventHandler CheckTransactionIDCompleted;
        
        /// <remarks/>
        public event CheckProductTypeCompletedEventHandler CheckProductTypeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/changePassword", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string changePassword(string user_id, string oldPassword, string newPassword, string confirmPassword) {
            object[] results = this.Invoke("changePassword", new object[] {
                        user_id,
                        oldPassword,
                        newPassword,
                        confirmPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void changePasswordAsync(string user_id, string oldPassword, string newPassword, string confirmPassword) {
            this.changePasswordAsync(user_id, oldPassword, newPassword, confirmPassword, null);
        }
        
        /// <remarks/>
        public void changePasswordAsync(string user_id, string oldPassword, string newPassword, string confirmPassword, object userState) {
            if ((this.changePasswordOperationCompleted == null)) {
                this.changePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangePasswordOperationCompleted);
            }
            this.InvokeAsync("changePassword", new object[] {
                        user_id,
                        oldPassword,
                        newPassword,
                        confirmPassword}, this.changePasswordOperationCompleted, userState);
        }
        
        private void OnchangePasswordOperationCompleted(object arg) {
            if ((this.changePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changePasswordCompleted(this, new changePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/CheckInformation", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckInformation(string type, string msisdn, string user_id, string user_pass) {
            object[] results = this.Invoke("CheckInformation", new object[] {
                        type,
                        msisdn,
                        user_id,
                        user_pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckInformationAsync(string type, string msisdn, string user_id, string user_pass) {
            this.CheckInformationAsync(type, msisdn, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void CheckInformationAsync(string type, string msisdn, string user_id, string user_pass, object userState) {
            if ((this.CheckInformationOperationCompleted == null)) {
                this.CheckInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckInformationOperationCompleted);
            }
            this.InvokeAsync("CheckInformation", new object[] {
                        type,
                        msisdn,
                        user_id,
                        user_pass}, this.CheckInformationOperationCompleted, userState);
        }
        
        private void OnCheckInformationOperationCompleted(object arg) {
            if ((this.CheckInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckInformationCompleted(this, new CheckInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/CheckBalance", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckBalance(string type, string msisdn, string user_id, string user_pass) {
            object[] results = this.Invoke("CheckBalance", new object[] {
                        type,
                        msisdn,
                        user_id,
                        user_pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBalanceAsync(string type, string msisdn, string user_id, string user_pass) {
            this.CheckBalanceAsync(type, msisdn, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void CheckBalanceAsync(string type, string msisdn, string user_id, string user_pass, object userState) {
            if ((this.CheckBalanceOperationCompleted == null)) {
                this.CheckBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBalanceOperationCompleted);
            }
            this.InvokeAsync("CheckBalance", new object[] {
                        type,
                        msisdn,
                        user_id,
                        user_pass}, this.CheckBalanceOperationCompleted, userState);
        }
        
        private void OnCheckBalanceOperationCompleted(object arg) {
            if ((this.CheckBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBalanceCompleted(this, new CheckBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/CheckBalanceNew", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultCheckBalanceNew CheckBalanceNew(string type, string msisdn, string user_id, string user_pass) {
            object[] results = this.Invoke("CheckBalanceNew", new object[] {
                        type,
                        msisdn,
                        user_id,
                        user_pass});
            return ((ResultCheckBalanceNew)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBalanceNewAsync(string type, string msisdn, string user_id, string user_pass) {
            this.CheckBalanceNewAsync(type, msisdn, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void CheckBalanceNewAsync(string type, string msisdn, string user_id, string user_pass, object userState) {
            if ((this.CheckBalanceNewOperationCompleted == null)) {
                this.CheckBalanceNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBalanceNewOperationCompleted);
            }
            this.InvokeAsync("CheckBalanceNew", new object[] {
                        type,
                        msisdn,
                        user_id,
                        user_pass}, this.CheckBalanceNewOperationCompleted, userState);
        }
        
        private void OnCheckBalanceNewOperationCompleted(object arg) {
            if ((this.CheckBalanceNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBalanceNewCompleted(this, new CheckBalanceNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/Payment", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public payments Payment(int type, string msisdn, double amount, string trans_id, string user_id, string user_pass) {
            object[] results = this.Invoke("Payment", new object[] {
                        type,
                        msisdn,
                        amount,
                        trans_id,
                        user_id,
                        user_pass});
            return ((payments)(results[0]));
        }
        
        /// <remarks/>
        public void PaymentAsync(int type, string msisdn, double amount, string trans_id, string user_id, string user_pass) {
            this.PaymentAsync(type, msisdn, amount, trans_id, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void PaymentAsync(int type, string msisdn, double amount, string trans_id, string user_id, string user_pass, object userState) {
            if ((this.PaymentOperationCompleted == null)) {
                this.PaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaymentOperationCompleted);
            }
            this.InvokeAsync("Payment", new object[] {
                        type,
                        msisdn,
                        amount,
                        trans_id,
                        user_id,
                        user_pass}, this.PaymentOperationCompleted, userState);
        }
        
        private void OnPaymentOperationCompleted(object arg) {
            if ((this.PaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaymentCompleted(this, new PaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/CancelReceipt", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CancelReceipts CancelReceipt(int type, string receipt, string user_id, string user_pass) {
            object[] results = this.Invoke("CancelReceipt", new object[] {
                        type,
                        receipt,
                        user_id,
                        user_pass});
            return ((CancelReceipts)(results[0]));
        }
        
        /// <remarks/>
        public void CancelReceiptAsync(int type, string receipt, string user_id, string user_pass) {
            this.CancelReceiptAsync(type, receipt, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void CancelReceiptAsync(int type, string receipt, string user_id, string user_pass, object userState) {
            if ((this.CancelReceiptOperationCompleted == null)) {
                this.CancelReceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelReceiptOperationCompleted);
            }
            this.InvokeAsync("CancelReceipt", new object[] {
                        type,
                        receipt,
                        user_id,
                        user_pass}, this.CancelReceiptOperationCompleted, userState);
        }
        
        private void OnCancelReceiptOperationCompleted(object arg) {
            if ((this.CancelReceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelReceiptCompleted(this, new CancelReceiptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/BuyTopup", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public topup BuyTopup(int card_type, string msisdn, string trans_id, string user_id, string user_pass) {
            object[] results = this.Invoke("BuyTopup", new object[] {
                        card_type,
                        msisdn,
                        trans_id,
                        user_id,
                        user_pass});
            return ((topup)(results[0]));
        }
        
        /// <remarks/>
        public void BuyTopupAsync(int card_type, string msisdn, string trans_id, string user_id, string user_pass) {
            this.BuyTopupAsync(card_type, msisdn, trans_id, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void BuyTopupAsync(int card_type, string msisdn, string trans_id, string user_id, string user_pass, object userState) {
            if ((this.BuyTopupOperationCompleted == null)) {
                this.BuyTopupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyTopupOperationCompleted);
            }
            this.InvokeAsync("BuyTopup", new object[] {
                        card_type,
                        msisdn,
                        trans_id,
                        user_id,
                        user_pass}, this.BuyTopupOperationCompleted, userState);
        }
        
        private void OnBuyTopupOperationCompleted(object arg) {
            if ((this.BuyTopupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyTopupCompleted(this, new BuyTopupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/BuyTopupFreeAmount", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultTopupFreeAmount BuyTopupFreeAmount(int Amount, string msisdn, string trans_id, string user_id, string user_pass) {
            object[] results = this.Invoke("BuyTopupFreeAmount", new object[] {
                        Amount,
                        msisdn,
                        trans_id,
                        user_id,
                        user_pass});
            return ((ResultTopupFreeAmount)(results[0]));
        }
        
        /// <remarks/>
        public void BuyTopupFreeAmountAsync(int Amount, string msisdn, string trans_id, string user_id, string user_pass) {
            this.BuyTopupFreeAmountAsync(Amount, msisdn, trans_id, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void BuyTopupFreeAmountAsync(int Amount, string msisdn, string trans_id, string user_id, string user_pass, object userState) {
            if ((this.BuyTopupFreeAmountOperationCompleted == null)) {
                this.BuyTopupFreeAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyTopupFreeAmountOperationCompleted);
            }
            this.InvokeAsync("BuyTopupFreeAmount", new object[] {
                        Amount,
                        msisdn,
                        trans_id,
                        user_id,
                        user_pass}, this.BuyTopupFreeAmountOperationCompleted, userState);
        }
        
        private void OnBuyTopupFreeAmountOperationCompleted(object arg) {
            if ((this.BuyTopupFreeAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyTopupFreeAmountCompleted(this, new BuyTopupFreeAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/checkBalanceCenter", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkBalanceCenter(string user_id, string user_pass) {
            object[] results = this.Invoke("checkBalanceCenter", new object[] {
                        user_id,
                        user_pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkBalanceCenterAsync(string user_id, string user_pass) {
            this.checkBalanceCenterAsync(user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void checkBalanceCenterAsync(string user_id, string user_pass, object userState) {
            if ((this.checkBalanceCenterOperationCompleted == null)) {
                this.checkBalanceCenterOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckBalanceCenterOperationCompleted);
            }
            this.InvokeAsync("checkBalanceCenter", new object[] {
                        user_id,
                        user_pass}, this.checkBalanceCenterOperationCompleted, userState);
        }
        
        private void OncheckBalanceCenterOperationCompleted(object arg) {
            if ((this.checkBalanceCenterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkBalanceCenterCompleted(this, new checkBalanceCenterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/checkBalanceCenterNew", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultCheckbalanceCenter checkBalanceCenterNew(string user_id, string user_pass) {
            object[] results = this.Invoke("checkBalanceCenterNew", new object[] {
                        user_id,
                        user_pass});
            return ((ResultCheckbalanceCenter)(results[0]));
        }
        
        /// <remarks/>
        public void checkBalanceCenterNewAsync(string user_id, string user_pass) {
            this.checkBalanceCenterNewAsync(user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void checkBalanceCenterNewAsync(string user_id, string user_pass, object userState) {
            if ((this.checkBalanceCenterNewOperationCompleted == null)) {
                this.checkBalanceCenterNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckBalanceCenterNewOperationCompleted);
            }
            this.InvokeAsync("checkBalanceCenterNew", new object[] {
                        user_id,
                        user_pass}, this.checkBalanceCenterNewOperationCompleted, userState);
        }
        
        private void OncheckBalanceCenterNewOperationCompleted(object arg) {
            if ((this.checkBalanceCenterNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkBalanceCenterNewCompleted(this, new checkBalanceCenterNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/CheckBalancePrepaid", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public checkmoney CheckBalancePrepaid(string msisdn, string user_id, string user_pass) {
            object[] results = this.Invoke("CheckBalancePrepaid", new object[] {
                        msisdn,
                        user_id,
                        user_pass});
            return ((checkmoney)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBalancePrepaidAsync(string msisdn, string user_id, string user_pass) {
            this.CheckBalancePrepaidAsync(msisdn, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void CheckBalancePrepaidAsync(string msisdn, string user_id, string user_pass, object userState) {
            if ((this.CheckBalancePrepaidOperationCompleted == null)) {
                this.CheckBalancePrepaidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBalancePrepaidOperationCompleted);
            }
            this.InvokeAsync("CheckBalancePrepaid", new object[] {
                        msisdn,
                        user_id,
                        user_pass}, this.CheckBalancePrepaidOperationCompleted, userState);
        }
        
        private void OnCheckBalancePrepaidOperationCompleted(object arg) {
            if ((this.CheckBalancePrepaidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBalancePrepaidCompleted(this, new CheckBalancePrepaidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/SendSMS", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultSentSMS SendSMS(string msisdn, string message, string user_id, string user_pass) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        msisdn,
                        message,
                        user_id,
                        user_pass});
            return ((ResultSentSMS)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(string msisdn, string message, string user_id, string user_pass) {
            this.SendSMSAsync(msisdn, message, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(string msisdn, string message, string user_id, string user_pass, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        msisdn,
                        message,
                        user_id,
                        user_pass}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/SendSMSHeader", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultSentSMS SendSMSHeader(string Header, string msisdn, string message, string user_id, string user_pass) {
            object[] results = this.Invoke("SendSMSHeader", new object[] {
                        Header,
                        msisdn,
                        message,
                        user_id,
                        user_pass});
            return ((ResultSentSMS)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSHeaderAsync(string Header, string msisdn, string message, string user_id, string user_pass) {
            this.SendSMSHeaderAsync(Header, msisdn, message, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void SendSMSHeaderAsync(string Header, string msisdn, string message, string user_id, string user_pass, object userState) {
            if ((this.SendSMSHeaderOperationCompleted == null)) {
                this.SendSMSHeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSHeaderOperationCompleted);
            }
            this.InvokeAsync("SendSMSHeader", new object[] {
                        Header,
                        msisdn,
                        message,
                        user_id,
                        user_pass}, this.SendSMSHeaderOperationCompleted, userState);
        }
        
        private void OnSendSMSHeaderOperationCompleted(object arg) {
            if ((this.SendSMSHeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSHeaderCompleted(this, new SendSMSHeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/QueryDetail", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryDetail(string query_type, string msisdn, string startDate, string endDate, string status, string user_id, string user_pass) {
            object[] results = this.Invoke("QueryDetail", new object[] {
                        query_type,
                        msisdn,
                        startDate,
                        endDate,
                        status,
                        user_id,
                        user_pass});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryDetailAsync(string query_type, string msisdn, string startDate, string endDate, string status, string user_id, string user_pass) {
            this.QueryDetailAsync(query_type, msisdn, startDate, endDate, status, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void QueryDetailAsync(string query_type, string msisdn, string startDate, string endDate, string status, string user_id, string user_pass, object userState) {
            if ((this.QueryDetailOperationCompleted == null)) {
                this.QueryDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryDetailOperationCompleted);
            }
            this.InvokeAsync("QueryDetail", new object[] {
                        query_type,
                        msisdn,
                        startDate,
                        endDate,
                        status,
                        user_id,
                        user_pass}, this.QueryDetailOperationCompleted, userState);
        }
        
        private void OnQueryDetailOperationCompleted(object arg) {
            if ((this.QueryDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryDetailCompleted(this, new QueryDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/QueryDetailMobile", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryDetailMobile(string query_type, string msisdn, string startDate, string stopDate, string status, string user_id, string user_pass) {
            object[] results = this.Invoke("QueryDetailMobile", new object[] {
                        query_type,
                        msisdn,
                        startDate,
                        stopDate,
                        status,
                        user_id,
                        user_pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryDetailMobileAsync(string query_type, string msisdn, string startDate, string stopDate, string status, string user_id, string user_pass) {
            this.QueryDetailMobileAsync(query_type, msisdn, startDate, stopDate, status, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void QueryDetailMobileAsync(string query_type, string msisdn, string startDate, string stopDate, string status, string user_id, string user_pass, object userState) {
            if ((this.QueryDetailMobileOperationCompleted == null)) {
                this.QueryDetailMobileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryDetailMobileOperationCompleted);
            }
            this.InvokeAsync("QueryDetailMobile", new object[] {
                        query_type,
                        msisdn,
                        startDate,
                        stopDate,
                        status,
                        user_id,
                        user_pass}, this.QueryDetailMobileOperationCompleted, userState);
        }
        
        private void OnQueryDetailMobileOperationCompleted(object arg) {
            if ((this.QueryDetailMobileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryDetailMobileCompleted(this, new QueryDetailMobileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/QueryDetailMasterSim", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultQueryDetail QueryDetailMasterSim(string msisdn, string query_type, string startDate, string endDate, string status, string user_id, string user_pass) {
            object[] results = this.Invoke("QueryDetailMasterSim", new object[] {
                        msisdn,
                        query_type,
                        startDate,
                        endDate,
                        status,
                        user_id,
                        user_pass});
            return ((resultQueryDetail)(results[0]));
        }
        
        /// <remarks/>
        public void QueryDetailMasterSimAsync(string msisdn, string query_type, string startDate, string endDate, string status, string user_id, string user_pass) {
            this.QueryDetailMasterSimAsync(msisdn, query_type, startDate, endDate, status, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void QueryDetailMasterSimAsync(string msisdn, string query_type, string startDate, string endDate, string status, string user_id, string user_pass, object userState) {
            if ((this.QueryDetailMasterSimOperationCompleted == null)) {
                this.QueryDetailMasterSimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryDetailMasterSimOperationCompleted);
            }
            this.InvokeAsync("QueryDetailMasterSim", new object[] {
                        msisdn,
                        query_type,
                        startDate,
                        endDate,
                        status,
                        user_id,
                        user_pass}, this.QueryDetailMasterSimOperationCompleted, userState);
        }
        
        private void OnQueryDetailMasterSimOperationCompleted(object arg) {
            if ((this.QueryDetailMasterSimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryDetailMasterSimCompleted(this, new QueryDetailMasterSimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/CheckTransactionID", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CheckTransactionResult CheckTransactionID(string trans_id, int type, string user_id, string user_pass) {
            object[] results = this.Invoke("CheckTransactionID", new object[] {
                        trans_id,
                        type,
                        user_id,
                        user_pass});
            return ((CheckTransactionResult)(results[0]));
        }
        
        /// <remarks/>
        public void CheckTransactionIDAsync(string trans_id, int type, string user_id, string user_pass) {
            this.CheckTransactionIDAsync(trans_id, type, user_id, user_pass, null);
        }
        
        /// <remarks/>
        public void CheckTransactionIDAsync(string trans_id, int type, string user_id, string user_pass, object userState) {
            if ((this.CheckTransactionIDOperationCompleted == null)) {
                this.CheckTransactionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckTransactionIDOperationCompleted);
            }
            this.InvokeAsync("CheckTransactionID", new object[] {
                        trans_id,
                        type,
                        user_id,
                        user_pass}, this.CheckTransactionIDOperationCompleted, userState);
        }
        
        private void OnCheckTransactionIDOperationCompleted(object arg) {
            if ((this.CheckTransactionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckTransactionIDCompleted(this, new CheckTransactionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.laotel.com/CheckProductType", RequestNamespace="http://services.laotel.com/", ResponseNamespace="http://services.laotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultProduct CheckProductType(string msisdn) {
            object[] results = this.Invoke("CheckProductType", new object[] {
                        msisdn});
            return ((ResultProduct)(results[0]));
        }
        
        /// <remarks/>
        public void CheckProductTypeAsync(string msisdn) {
            this.CheckProductTypeAsync(msisdn, null);
        }
        
        /// <remarks/>
        public void CheckProductTypeAsync(string msisdn, object userState) {
            if ((this.CheckProductTypeOperationCompleted == null)) {
                this.CheckProductTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckProductTypeOperationCompleted);
            }
            this.InvokeAsync("CheckProductType", new object[] {
                        msisdn}, this.CheckProductTypeOperationCompleted, userState);
        }
        
        private void OnCheckProductTypeOperationCompleted(object arg) {
            if ((this.CheckProductTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckProductTypeCompleted(this, new CheckProductTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class ResultCheckBalanceNew {
        
        private string errCodeField;
        
        private string errDescField;
        
        private double amountField;
        
        /// <remarks/>
        public string ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class ResultProduct {
        
        private string resultCodeField;
        
        private string resultDescField;
        
        private string networkCodeField;
        
        private string networkNameField;
        
        private string productTypeField;
        
        /// <remarks/>
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string resultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public string networkCode {
            get {
                return this.networkCodeField;
            }
            set {
                this.networkCodeField = value;
            }
        }
        
        /// <remarks/>
        public string networkName {
            get {
                return this.networkNameField;
            }
            set {
                this.networkNameField = value;
            }
        }
        
        /// <remarks/>
        public string productType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class ResultTransationTopup {
        
        private string p_USER_IDField;
        
        private string p_SEQ_NUMBERField;
        
        private string p_FRECEIPTField;
        
        private string p_CENTER_NUMBERField;
        
        private string p_MSISDNField;
        
        private long p_AMOUNTField;
        
        private string p_STATUSField;
        
        private System.DateTime p_RECORD_DATEField;
        
        /// <remarks/>
        public string P_USER_ID {
            get {
                return this.p_USER_IDField;
            }
            set {
                this.p_USER_IDField = value;
            }
        }
        
        /// <remarks/>
        public string P_SEQ_NUMBER {
            get {
                return this.p_SEQ_NUMBERField;
            }
            set {
                this.p_SEQ_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string P_FRECEIPT {
            get {
                return this.p_FRECEIPTField;
            }
            set {
                this.p_FRECEIPTField = value;
            }
        }
        
        /// <remarks/>
        public string P_CENTER_NUMBER {
            get {
                return this.p_CENTER_NUMBERField;
            }
            set {
                this.p_CENTER_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string P_MSISDN {
            get {
                return this.p_MSISDNField;
            }
            set {
                this.p_MSISDNField = value;
            }
        }
        
        /// <remarks/>
        public long P_AMOUNT {
            get {
                return this.p_AMOUNTField;
            }
            set {
                this.p_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string P_STATUS {
            get {
                return this.p_STATUSField;
            }
            set {
                this.p_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime P_RECORD_DATE {
            get {
                return this.p_RECORD_DATEField;
            }
            set {
                this.p_RECORD_DATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class ResultTransationPayment {
        
        private string p_USER_IDField;
        
        private string p_SEQ_NUMBERField;
        
        private int p_TYPEField;
        
        private string p_PAYMENT_IDField;
        
        private string p_MSISDNField;
        
        private long p_AMOUNTField;
        
        private string p_STATUSField;
        
        private System.DateTime p_RECORD_DATEField;
        
        private string p_RECEIPT_NOField;
        
        /// <remarks/>
        public string P_USER_ID {
            get {
                return this.p_USER_IDField;
            }
            set {
                this.p_USER_IDField = value;
            }
        }
        
        /// <remarks/>
        public string P_SEQ_NUMBER {
            get {
                return this.p_SEQ_NUMBERField;
            }
            set {
                this.p_SEQ_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public int P_TYPE {
            get {
                return this.p_TYPEField;
            }
            set {
                this.p_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string P_PAYMENT_ID {
            get {
                return this.p_PAYMENT_IDField;
            }
            set {
                this.p_PAYMENT_IDField = value;
            }
        }
        
        /// <remarks/>
        public string P_MSISDN {
            get {
                return this.p_MSISDNField;
            }
            set {
                this.p_MSISDNField = value;
            }
        }
        
        /// <remarks/>
        public long P_AMOUNT {
            get {
                return this.p_AMOUNTField;
            }
            set {
                this.p_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string P_STATUS {
            get {
                return this.p_STATUSField;
            }
            set {
                this.p_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime P_RECORD_DATE {
            get {
                return this.p_RECORD_DATEField;
            }
            set {
                this.p_RECORD_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string P_RECEIPT_NO {
            get {
                return this.p_RECEIPT_NOField;
            }
            set {
                this.p_RECEIPT_NOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class ResultTransaction {
        
        private bool statusField;
        
        private ResultTransationPayment resultPaymentField;
        
        private ResultTransationTopup resultTopupField;
        
        /// <remarks/>
        public bool status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public ResultTransationPayment ResultPayment {
            get {
                return this.resultPaymentField;
            }
            set {
                this.resultPaymentField = value;
            }
        }
        
        /// <remarks/>
        public ResultTransationTopup ResultTopup {
            get {
                return this.resultTopupField;
            }
            set {
                this.resultTopupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class CheckTransactionResult {
        
        private ResultTransaction transactionDetailField;
        
        private string errDescField;
        
        /// <remarks/>
        public ResultTransaction TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public string errDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class resultQueryDetail {
        
        private string errCodeField;
        
        private string errDescField;
        
        private System.Data.DataSet resultField;
        
        /// <remarks/>
        public string ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class ResultSentSMS {
        
        private int errCodeField;
        
        private string errDescField;
        
        private string msisdnField;
        
        private string sMSField;
        
        private string userIDField;
        
        /// <remarks/>
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public string Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string SMS {
            get {
                return this.sMSField;
            }
            set {
                this.sMSField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class checkmoney {
        
        private string msisdnField;
        
        private int errCodeField;
        
        private string errDescField;
        
        private double balanceField;
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public int errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public double balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class ResultCheckbalanceCenter {
        
        private string errCodeField;
        
        private string errDescField;
        
        private double balanceField;
        
        /// <remarks/>
        public string ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class ResultTopupFreeAmount {
        
        private int errCodeField;
        
        private string errDescField;
        
        private string receiptField;
        
        private string msisdnField;
        
        private double amountField;
        
        private string userIDField;
        
        /// <remarks/>
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public string Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        public string Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class topup {
        
        private int errCodeField;
        
        private string errDescField;
        
        private string receiptField;
        
        private string msisdnField;
        
        private double amountField;
        
        private string userIDField;
        
        /// <remarks/>
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public string Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        public string Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class CancelReceipts {
        
        private int errCodeField;
        
        private string errDescField;
        
        private string msisdnField;
        
        private string receiptField;
        
        private double amountField;
        
        private string userIDField;
        
        /// <remarks/>
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public string Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.laotel.com/")]
    public partial class payments {
        
        private int errCodeField;
        
        private string errDescField;
        
        private string msisdnField;
        
        private string receiptField;
        
        private double amountField;
        
        private string userIDField;
        
        /// <remarks/>
        public int ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
        
        /// <remarks/>
        public string Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void changePasswordCompletedEventHandler(object sender, changePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckInformationCompletedEventHandler(object sender, CheckInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckBalanceCompletedEventHandler(object sender, CheckBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckBalanceNewCompletedEventHandler(object sender, CheckBalanceNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBalanceNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBalanceNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultCheckBalanceNew Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultCheckBalanceNew)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PaymentCompletedEventHandler(object sender, PaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public payments Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((payments)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CancelReceiptCompletedEventHandler(object sender, CancelReceiptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelReceiptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelReceiptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelReceipts Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelReceipts)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuyTopupCompletedEventHandler(object sender, BuyTopupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuyTopupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuyTopupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public topup Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((topup)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuyTopupFreeAmountCompletedEventHandler(object sender, BuyTopupFreeAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuyTopupFreeAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuyTopupFreeAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultTopupFreeAmount Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultTopupFreeAmount)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void checkBalanceCenterCompletedEventHandler(object sender, checkBalanceCenterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkBalanceCenterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkBalanceCenterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void checkBalanceCenterNewCompletedEventHandler(object sender, checkBalanceCenterNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkBalanceCenterNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkBalanceCenterNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultCheckbalanceCenter Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultCheckbalanceCenter)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckBalancePrepaidCompletedEventHandler(object sender, CheckBalancePrepaidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBalancePrepaidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBalancePrepaidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public checkmoney Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((checkmoney)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultSentSMS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultSentSMS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMSHeaderCompletedEventHandler(object sender, SendSMSHeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSHeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSHeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultSentSMS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultSentSMS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void QueryDetailCompletedEventHandler(object sender, QueryDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void QueryDetailMobileCompletedEventHandler(object sender, QueryDetailMobileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryDetailMobileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryDetailMobileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void QueryDetailMasterSimCompletedEventHandler(object sender, QueryDetailMasterSimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryDetailMasterSimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryDetailMasterSimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultQueryDetail Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultQueryDetail)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckTransactionIDCompletedEventHandler(object sender, CheckTransactionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckTransactionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckTransactionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckTransactionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckTransactionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckProductTypeCompletedEventHandler(object sender, CheckProductTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckProductTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckProductTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultProduct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultProduct)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591